import { areaSummaries, homeSteps, institutionalSteps, values } from '../src/lib/marketingContent'
import { bpcAudience, bpcCards, bpcFaq, licitacoesFaq, licitacoesServices, licitacoesShortServices, previdenciarioFaq, previdenciarioServices, trabalhoFaq, trabalhoServices } from '../src/lib/areaPages'

const cards = (items: any[]) => items.map(({ description, icon, title }: any) => ({ descricao: description, icone: icon, titulo: title }))
const steps = (items: any[]) => items.map(({ description, title }: any) => ({ descricao: description, titulo: title }))
const faqs = (items: any[]) => items.map(({ answer, question }: any) => ({ pergunta: question, resposta: answer }))
const common = { notaHero: 'Atendimento humanizado e sigiloso', faqChapeu: 'Dúvidas frequentes', faqTitulo: 'Perguntas comuns', cta: { chapeu: 'Fale comigo', texto: 'Atendimento online para todo o Brasil.', botao: 'Fale comigo no WhatsApp' } }

export const siteContentBaseline = {
  seedAplicado: true,
  compartilhados: { logoAlt: 'Deila Pinto Advocacia e Consultoria', whatsappBotao: 'Fale no WhatsApp', menu: [{ rotulo: 'Início', link: '/' }, { rotulo: 'Sobre', link: '/sobre' }, { rotulo: 'Áreas de Atuação', link: '/areas-de-atuacao', mostrarAreas: true }, { rotulo: 'Como Funciona', link: '/#como-funciona' }, { rotulo: 'Blog', link: '/blog' }, { rotulo: 'Contato', link: '/contato' }], rodapeResumo: 'Advocacia com propósito, técnica e sensibilidade para defender o que é seu por direito.', rodapeAreasTitulo: 'Áreas de atuação', rodapeInstitucionalTitulo: 'Institucional', rodapeAtendimentoTitulo: 'Atendimento', rodapeHorarioTitulo: 'Horário de atendimento', rodapeLocais: [{ texto: 'Goianinha/RN' }, { texto: 'Atendimento também em Natal/RN' }], cta: { chapeu: 'Contato', titulo: 'Vamos conversar sobre o seu direito?', texto: 'Atendimento online para todo o Brasil.', botao: 'Fale comigo no WhatsApp' } },
  home: { heroChapeu: 'Advocacia com propósito', heroLinha1: 'Orientação jurídica', heroLinha2Antes: 'com', heroLinha2Destaque: 'clareza, atenção', heroLinha3: 'e responsabilidade', heroTexto: 'Atendimento em Direito Previdenciário, BPC/LOAS, Direito do Trabalho, Licitações e Contratos para organizar informações, orientar decisões e oferecer atendimento jurídico próximo e responsável.', heroNota: 'Atendimento humanizado e sigiloso', areasChapeu: 'Áreas de atuação', areasTitulo: 'Como posso te ajudar', bannersChapeu: 'Atendimento por área', bannersTitulo: 'Caminhos de orientação', sobreChapeu: 'Quem vai atender você', sobreTitulo: 'Prazer, eu sou Deila Pinto', sobreParagrafos: [{ texto: 'Advogada inscrita na OAB/RN 22.940, com atuação voltada a demandas previdenciárias, assistenciais, trabalhistas, licitações e contratos.' }, { texto: 'A primeira conversa busca entender o caso com linguagem clara, cuidado com documentos e respeito ao momento de cada pessoa.' }], sobreBotao: 'Me conhecer melhor', processoChapeu: 'Como funciona', processoTitulo: 'Um atendimento em 3 passos', processoEtapas: steps(homeSteps), cta: { chapeu: 'Vamos conversar?', titulo: 'Inicie pelo caminho mais simples.', texto: 'O WhatsApp preserva o assunto escolhido e facilita a continuidade da conversa.', botao: 'Fale comigo no WhatsApp' } },
  sobre: { heroChapeu: 'Sobre', heroTitulo: 'Sobre', heroTexto: 'Conheça a trajetória, os valores e o propósito que guiam cada atendimento.', bioChapeu: 'Quem é Deila Pinto', bioTitulo: 'Advocacia com propósito, escuta e excelência.', bioParagrafos: [{ texto: 'Deila Pinto é advogada inscrita na OAB/RN 22.940, com atuação em Direito Previdenciário, BPC/LOAS, Direito do Trabalho, Licitações e Contratos.' }, { texto: 'A proposta do atendimento é unir técnica, clareza e cuidado na organização das informações, documentos e próximos passos.' }], bioBotaoSecundario: 'Agendar atendimento', valoresChapeu: 'Nossos valores', valoresTitulo: 'Princípios que orientam cada passo', valores: cards(values), processoChapeu: 'Nossa forma de atuar', processoTitulo: 'Um atendimento próximo e estratégico', processoEtapas: steps(institutionalSteps), areasChapeu: 'Áreas de atuação', areasTitulo: 'Atuação especializada com atenção aos detalhes', areasBotao: 'Ver todas as áreas', cta: { chapeu: 'Contato', titulo: 'Vamos conversar sobre o seu caso?', texto: 'Atendimento online para todo o Brasil.', botao: 'Fale comigo no WhatsApp' } },
  contato: { heroChapeu: 'Vamos conversar?', heroTitulo: 'Contato', heroTexto: 'Estamos aqui para ouvir você e encontrar o melhor caminho para o seu caso.', heroNota: 'Atendimento humanizado e sigiloso.', metodosTitulo: 'Outras formas de contato', whatsappTitulo: 'Atendimento via WhatsApp', whatsappAcao: 'Iniciar conversa', emailTitulo: 'E-mail', localizacaoTitulo: 'Localização', localizacaoFallback: 'Endereço confirmado pelo atendimento.', horarioTitulo: 'Horário de atendimento', horarioFallback: 'Mediante agendamento.', areasChapeu: 'Áreas', areasTitulo: 'Assuntos atendidos', faqChapeu: 'Dúvidas frequentes', faqTitulo: 'Antes do primeiro contato', faq: [{ pergunta: 'Como funciona o atendimento online?', resposta: 'O atendimento inicial organiza o relato e os documentos para avaliar os próximos passos.' }, { pergunta: 'Quais informações preciso enviar inicialmente?', resposta: 'Nome, telefone, assunto, mensagem e documentos relacionados podem ajudar na conversa.' }, { pergunta: 'Qual o prazo para retorno?', resposta: 'O retorno depende da agenda e da complexidade das informações enviadas.' }], segurancaChapeu: 'Segurança', segurancaTitulo: 'Antes de enviar qualquer dado sensível.' },
  areas: { heroChapeu: 'Atendimento humanizado e especializado', heroTitulo: 'Áreas de atuação', heroTexto: 'Atuação jurídica com clareza, atenção e responsabilidade para proteger seus direitos e trazer tranquilidade.', editorialChapeu: 'Atuação que faz a diferença', editorialTitulo: 'Assessoria jurídica feita para entender você e o seu caso', editorialTexto: 'Cada pessoa tem uma história e cada caso exige atenção aos detalhes. Por isso, a conversa inicial organiza informações e documentos antes de qualquer providência.', destaques: [{ texto: 'Escuta e análise', icone: 'search' }, { texto: 'Clareza em cada etapa', icone: 'document' }, { texto: 'Acompanhamento', icone: 'checklist' }], processoChapeu: 'Como funciona', processoTitulo: 'Um atendimento em 3 passos', processoEtapas: steps(homeSteps), cta: { chapeu: 'Contato', titulo: 'Dê o primeiro passo para proteger seus direitos.', texto: 'Atendimento online para todo o Brasil.', botao: 'Fale comigo no WhatsApp' } },
  paginasArea: [
    { ...common, slug: 'direito-previdenciario', titulo: 'Direito Previdenciário', chapeu: 'Áreas de atuação', descricao: areaSummaries[0].description, icone: 'protection', servicosChapeu: 'Como podemos ajudar', servicosTitulo: 'Soluções para cada momento da sua vida', servicos: cards(previdenciarioServices), processoChapeu: 'Como funciona', processoTitulo: 'Um atendimento claro e eficiente', processoEtapas: steps(homeSteps), faq: faqs(previdenciarioFaq), cta: { ...common.cta, titulo: 'Precisa de orientação sobre seu benefício previdenciário?' } },
    { ...common, slug: 'bpc-loas', titulo: 'BPC/LOAS', chapeu: 'Direito assistencial', descricao: areaSummaries[1].description, icone: 'bpc', servicosChapeu: 'Como podemos ajudar', servicosTitulo: 'Como posso te ajudar', servicos: cards(bpcCards), publicoTitulo: 'Quem pode ter direito?', publicos: cards(bpcAudience), processoChapeu: 'Como funciona', processoTitulo: 'Como funciona o atendimento', processoEtapas: steps(homeSteps), faq: faqs(bpcFaq), cta: { ...common.cta, titulo: 'Precisa de ajuda para solicitar o BPC/LOAS?' } },
    { ...common, slug: 'direito-do-trabalho', titulo: 'Direito do Trabalho', chapeu: 'Áreas de atuação', descricao: areaSummaries[2].description, icone: 'briefcase', servicosChapeu: 'Como podemos ajudar', servicosTitulo: 'Como posso te ajudar', servicos: cards(trabalhoServices), extrasChapeu: 'Situações em que podemos ajudar', situacoes: ['Demissão sem pagamento correto', 'Não pagamento de horas extras', 'Desvio ou acúmulo de função', 'Ambiente de trabalho hostil', 'Acidente ou doença relacionada ao trabalho', 'Negativa de direitos ou benefícios'].map((texto) => ({ texto })), documentosTitulo: 'Documentos que podem ser necessários', documentos: ['Carteira de trabalho física ou digital', 'Contracheques e comprovantes de pagamento', 'Contrato de trabalho, se houver', 'Comprovantes de jornada e mensagens'].map((texto) => ({ texto })), processoChapeu: 'Como funciona', processoTitulo: 'Como funciona o atendimento', processoEtapas: steps(homeSteps), faq: faqs(trabalhoFaq), cta: { ...common.cta, titulo: 'Fale direto comigo no WhatsApp' } },
    { ...common, slug: 'licitacoes-e-contratos', titulo: 'Licitações e Contratos', tituloDestaque: 'Contratos', chapeu: 'Áreas de atuação', descricao: areaSummaries[3].description, icone: 'contract', servicosChapeu: 'Nossa atuação', servicosTitulo: 'Como podemos assessorar', servicos: cards(licitacoesServices), processoChapeu: 'Etapas da assessoria', processoTitulo: 'Etapas da assessoria', processoEtapas: steps(institutionalSteps), extrasChapeu: 'O que fazemos', extrasTitulo: 'Serviços mais procurados', extras: cards(licitacoesShortServices), faq: faqs(licitacoesFaq), cta: { ...common.cta, titulo: 'Precisa de orientação em uma licitação ou contrato administrativo?' } },
  ],
}
