/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'lead-submissions': LeadSubmission;
    campaigns: Campaign;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'lead-submissions': LeadSubmissionsSelect<false> | LeadSubmissionsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-config': SiteConfig;
    'site-content': SiteContent;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-submissions".
 */
export interface LeadSubmission {
  id: number;
  idempotencia: string;
  enviadoEm: string;
  escritorio: 'DP';
  telefone: string;
  nome?: string | null;
  email?: string | null;
  campanha?: string | null;
  origem: 'landing' | 'contato' | 'calculadora';
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    content?: string | null;
    term?: string | null;
  };
  referrer?: string | null;
  respostas?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  consentAceito?: boolean | null;
  consentVersao?: string | null;
  consentEm?: string | null;
  consentIp?: string | null;
  status: 'pendente' | 'entregue' | 'rejeitada' | 'falha';
  tentativas?: number | null;
  ultimoErro?: string | null;
  leadIdCrm?: string | null;
  /**
   * Registro criado pela etapa 1 do formulario, antes do consentimento.
   */
  capturaParcial?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  /**
   * Código criado primeiro no EspoCRM. Copie de lá.
   */
  campaignCode: string;
  /**
   * Categoria editorial exibida na listagem e na landing.
   */
  categoria: 'previdenciario' | 'assistencial' | 'trabalhista' | 'licitacoes';
  slug: string;
  temLanding?: boolean | null;
  titulo?: string | null;
  subtitulo?: string | null;
  apresentacao?: {
    blocoDorTitulo?: string | null;
    blocoProvaTitulo?: string | null;
    blocoOrientacaoTitulo?: string | null;
    videoEyebrow?: string | null;
    videoTitulo?: string | null;
    videoDescricao?: string | null;
    faqEyebrow?: string | null;
    faqTitulo?: string | null;
    faqDescricao?: string | null;
    notaCuidado?: string | null;
    etapasContato?:
      | {
          titulo: string;
          id?: string | null;
        }[]
      | null;
    ctaFormulario?: string | null;
    ctaWhatsapp?: string | null;
    formularioTituloWhatsapp?: string | null;
    formularioTextoWhatsapp?: string | null;
    triagemEyebrow?: string | null;
    triagemTitulo?: string | null;
    triagemVaziaTitulo?: string | null;
    triagemVaziaTexto?: string | null;
    midiaFallback?: (number | null) | Media;
    seloMarca?: (number | null) | Media;
  };
  midiaTopo?: (number | null) | Media;
  blocoDor?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocoProva?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Como a equipe pode orientar a análise inicial, sem prometer resultado.
   */
  blocoOrientacao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Link opcional de vídeo do YouTube ou Vimeo para a campanha.
   */
  videoUrl?: string | null;
  /**
   * Vídeo curto em MP4. Se preenchido, aparece no bloco de vídeo da página.
   */
  videoFile?: (number | null) | Media;
  /**
   * Aviso objetivo sobre prazo ou documento. Evite pressão artificial.
   */
  textoUrgencia?: string | null;
  /**
   * Exibe o formulário de primeiro contato nesta campanha.
   */
  mostrarFormulario?: boolean | null;
  /**
   * Dúvidas frequentes específicas desta campanha.
   */
  faq?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  perguntas?:
    | {
        pergunta: string;
        tipo: 'texto' | 'data' | 'opcoes';
        opcoes?:
          | {
              opcao: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  mensagemWhatsapp?: string | null;
  seo?: {
    titulo?: string | null;
    descricao?: string | null;
    ogImage?: (number | null) | Media;
  };
  status: 'rascunho' | 'publicada';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  category: string;
  excerpt: string;
  author: string;
  publishedAt?: string | null;
  readingTime?: string | null;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'lead-submissions';
        value: number | LeadSubmission;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-submissions_select".
 */
export interface LeadSubmissionsSelect<T extends boolean = true> {
  idempotencia?: T;
  enviadoEm?: T;
  escritorio?: T;
  telefone?: T;
  nome?: T;
  email?: T;
  campanha?: T;
  origem?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        content?: T;
        term?: T;
      };
  referrer?: T;
  respostas?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  consentAceito?: T;
  consentVersao?: T;
  consentEm?: T;
  consentIp?: T;
  status?: T;
  tentativas?: T;
  ultimoErro?: T;
  leadIdCrm?: T;
  capturaParcial?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  campaignCode?: T;
  categoria?: T;
  slug?: T;
  temLanding?: T;
  titulo?: T;
  subtitulo?: T;
  apresentacao?:
    | T
    | {
        blocoDorTitulo?: T;
        blocoProvaTitulo?: T;
        blocoOrientacaoTitulo?: T;
        videoEyebrow?: T;
        videoTitulo?: T;
        videoDescricao?: T;
        faqEyebrow?: T;
        faqTitulo?: T;
        faqDescricao?: T;
        notaCuidado?: T;
        etapasContato?:
          | T
          | {
              titulo?: T;
              id?: T;
            };
        ctaFormulario?: T;
        ctaWhatsapp?: T;
        formularioTituloWhatsapp?: T;
        formularioTextoWhatsapp?: T;
        triagemEyebrow?: T;
        triagemTitulo?: T;
        triagemVaziaTitulo?: T;
        triagemVaziaTexto?: T;
        midiaFallback?: T;
        seloMarca?: T;
      };
  midiaTopo?: T;
  blocoDor?: T;
  blocoProva?: T;
  blocoOrientacao?: T;
  videoUrl?: T;
  videoFile?: T;
  textoUrgencia?: T;
  mostrarFormulario?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  perguntas?:
    | T
    | {
        pergunta?: T;
        tipo?: T;
        opcoes?:
          | T
          | {
              opcao?: T;
              id?: T;
            };
        id?: T;
      };
  mensagemWhatsapp?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        ogImage?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  author?: T;
  publishedAt?: T;
  readingTime?: T;
  coverImage?: T;
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  razaoSocial: string;
  titular: string;
  oab: string;
  cnpj?: string | null;
  endereco?:
    | {
        cidade?: string | null;
        uf?: string | null;
        logradouro?: string | null;
        bairro?: string | null;
        cep?: string | null;
        id?: string | null;
      }[]
    | null;
  telefoneWhatsapp: string;
  telefoneFixo?: string | null;
  emails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  instagram?: string | null;
  facebook?: string | null;
  areasDeAtuacao?:
    | {
        nome: string;
        id?: string | null;
      }[]
    | null;
  horarioAtendimento?: string | null;
  textoConsentimento: string;
  consentimentoVersao: string;
  /**
   * Texto exibido no atalho fixo para /ir/whatsapp?c=PREV-EXIGENCIA.
   */
  urgenciaTexto?: string | null;
  /**
   * Aviso sobre senhas do gov.br, Meu INSS, banco e codigos de SMS. Texto fornecido pelo escritorio.
   */
  avisoGolpeTexto?: string | null;
  marca?: {
    logo?: (number | null) | Media;
    logoClaro?: (number | null) | Media;
    favicon?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  seedAplicado?: boolean | null;
  compartilhados: {
    logoAlt: string;
    whatsappBotao: string;
    menu?:
      | {
          rotulo: string;
          link: string;
          mostrarAreas?: boolean | null;
          id?: string | null;
        }[]
      | null;
    rodapeResumo: string;
    rodapeAreasTitulo: string;
    rodapeInstitucionalTitulo: string;
    rodapeAtendimentoTitulo: string;
    rodapeHorarioTitulo: string;
    rodapeLocais?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    cta: {
      chapeu: string;
      titulo: string;
      texto: string;
      botao: string;
    };
  };
  home: {
    heroChapeu: string;
    heroLinha1: string;
    heroLinha2Antes: string;
    heroLinha2Destaque: string;
    heroLinha3: string;
    heroTexto: string;
    heroNota: string;
    heroImagem?: (number | null) | Media;
    areasChapeu: string;
    areasTitulo: string;
    bannersChapeu: string;
    bannersTitulo: string;
    sobreChapeu: string;
    sobreTitulo: string;
    sobreParagrafos?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    sobreBotao: string;
    sobreImagem?: (number | null) | Media;
    processoChapeu: string;
    processoTitulo: string;
    processoEtapas?:
      | {
          titulo: string;
          descricao: string;
          id?: string | null;
        }[]
      | null;
    cta: {
      chapeu: string;
      titulo: string;
      texto: string;
      botao: string;
    };
  };
  sobre: {
    heroChapeu: string;
    heroTitulo: string;
    heroTexto: string;
    heroImagem?: (number | null) | Media;
    bioChapeu: string;
    bioTitulo: string;
    bioParagrafos?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    bioImagem?: (number | null) | Media;
    bioBotaoSecundario: string;
    valoresChapeu: string;
    valoresTitulo: string;
    valores?:
      | {
          titulo: string;
          descricao: string;
          /**
           * Nome do ícone da identidade visual (ex.: protection, document, checklist).
           */
          icone?: string | null;
          id?: string | null;
        }[]
      | null;
    processoChapeu: string;
    processoTitulo: string;
    processoEtapas?:
      | {
          titulo: string;
          descricao: string;
          id?: string | null;
        }[]
      | null;
    areasChapeu: string;
    areasTitulo: string;
    areasBotao: string;
    cta: {
      chapeu: string;
      titulo: string;
      texto: string;
      botao: string;
    };
  };
  contato: {
    heroChapeu: string;
    heroTitulo: string;
    heroTexto: string;
    heroNota: string;
    heroImagem?: (number | null) | Media;
    metodosTitulo: string;
    whatsappTitulo: string;
    whatsappAcao: string;
    emailTitulo: string;
    localizacaoTitulo: string;
    localizacaoFallback: string;
    horarioTitulo: string;
    horarioFallback: string;
    areasChapeu: string;
    areasTitulo: string;
    faqChapeu: string;
    faqTitulo: string;
    faq?:
      | {
          pergunta: string;
          resposta: string;
          id?: string | null;
        }[]
      | null;
    segurancaChapeu: string;
    segurancaTitulo: string;
  };
  areas: {
    heroChapeu: string;
    heroTitulo: string;
    heroTexto: string;
    heroImagem?: (number | null) | Media;
    editorialChapeu: string;
    editorialTitulo: string;
    editorialTexto: string;
    editorialImagem?: (number | null) | Media;
    destaques?:
      | {
          texto: string;
          icone: string;
          id?: string | null;
        }[]
      | null;
    processoChapeu: string;
    processoTitulo: string;
    processoEtapas?:
      | {
          titulo: string;
          descricao: string;
          id?: string | null;
        }[]
      | null;
    cta: {
      chapeu: string;
      titulo: string;
      texto: string;
      botao: string;
    };
  };
  paginasArea?:
    | {
        slug: 'direito-previdenciario' | 'bpc-loas' | 'direito-do-trabalho' | 'licitacoes-e-contratos';
        titulo: string;
        tituloDestaque?: string | null;
        chapeu: string;
        descricao: string;
        icone: string;
        notaHero: string;
        servicosChapeu: string;
        servicosTitulo: string;
        servicos?:
          | {
              titulo: string;
              descricao: string;
              /**
               * Nome do ícone da identidade visual (ex.: protection, document, checklist).
               */
              icone?: string | null;
              id?: string | null;
            }[]
          | null;
        publicoTitulo?: string | null;
        publicos?:
          | {
              titulo: string;
              descricao: string;
              /**
               * Nome do ícone da identidade visual (ex.: protection, document, checklist).
               */
              icone?: string | null;
              id?: string | null;
            }[]
          | null;
        processoChapeu: string;
        processoTitulo: string;
        processoEtapas?:
          | {
              titulo: string;
              descricao: string;
              id?: string | null;
            }[]
          | null;
        extrasChapeu?: string | null;
        extrasTitulo?: string | null;
        extras?:
          | {
              titulo: string;
              descricao: string;
              /**
               * Nome do ícone da identidade visual (ex.: protection, document, checklist).
               */
              icone?: string | null;
              id?: string | null;
            }[]
          | null;
        faqChapeu: string;
        faqTitulo: string;
        faq?:
          | {
              pergunta: string;
              resposta: string;
              id?: string | null;
            }[]
          | null;
        cta: {
          chapeu: string;
          titulo: string;
          texto: string;
          botao: string;
        };
        situacoes?:
          | {
              texto: string;
              id?: string | null;
            }[]
          | null;
        documentosTitulo?: string | null;
        documentos?:
          | {
              texto: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  razaoSocial?: T;
  titular?: T;
  oab?: T;
  cnpj?: T;
  endereco?:
    | T
    | {
        cidade?: T;
        uf?: T;
        logradouro?: T;
        bairro?: T;
        cep?: T;
        id?: T;
      };
  telefoneWhatsapp?: T;
  telefoneFixo?: T;
  emails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  instagram?: T;
  facebook?: T;
  areasDeAtuacao?:
    | T
    | {
        nome?: T;
        id?: T;
      };
  horarioAtendimento?: T;
  textoConsentimento?: T;
  consentimentoVersao?: T;
  urgenciaTexto?: T;
  avisoGolpeTexto?: T;
  marca?:
    | T
    | {
        logo?: T;
        logoClaro?: T;
        favicon?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  seedAplicado?: T;
  compartilhados?:
    | T
    | {
        logoAlt?: T;
        whatsappBotao?: T;
        menu?:
          | T
          | {
              rotulo?: T;
              link?: T;
              mostrarAreas?: T;
              id?: T;
            };
        rodapeResumo?: T;
        rodapeAreasTitulo?: T;
        rodapeInstitucionalTitulo?: T;
        rodapeAtendimentoTitulo?: T;
        rodapeHorarioTitulo?: T;
        rodapeLocais?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              chapeu?: T;
              titulo?: T;
              texto?: T;
              botao?: T;
            };
      };
  home?:
    | T
    | {
        heroChapeu?: T;
        heroLinha1?: T;
        heroLinha2Antes?: T;
        heroLinha2Destaque?: T;
        heroLinha3?: T;
        heroTexto?: T;
        heroNota?: T;
        heroImagem?: T;
        areasChapeu?: T;
        areasTitulo?: T;
        bannersChapeu?: T;
        bannersTitulo?: T;
        sobreChapeu?: T;
        sobreTitulo?: T;
        sobreParagrafos?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        sobreBotao?: T;
        sobreImagem?: T;
        processoChapeu?: T;
        processoTitulo?: T;
        processoEtapas?:
          | T
          | {
              titulo?: T;
              descricao?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              chapeu?: T;
              titulo?: T;
              texto?: T;
              botao?: T;
            };
      };
  sobre?:
    | T
    | {
        heroChapeu?: T;
        heroTitulo?: T;
        heroTexto?: T;
        heroImagem?: T;
        bioChapeu?: T;
        bioTitulo?: T;
        bioParagrafos?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        bioImagem?: T;
        bioBotaoSecundario?: T;
        valoresChapeu?: T;
        valoresTitulo?: T;
        valores?:
          | T
          | {
              titulo?: T;
              descricao?: T;
              icone?: T;
              id?: T;
            };
        processoChapeu?: T;
        processoTitulo?: T;
        processoEtapas?:
          | T
          | {
              titulo?: T;
              descricao?: T;
              id?: T;
            };
        areasChapeu?: T;
        areasTitulo?: T;
        areasBotao?: T;
        cta?:
          | T
          | {
              chapeu?: T;
              titulo?: T;
              texto?: T;
              botao?: T;
            };
      };
  contato?:
    | T
    | {
        heroChapeu?: T;
        heroTitulo?: T;
        heroTexto?: T;
        heroNota?: T;
        heroImagem?: T;
        metodosTitulo?: T;
        whatsappTitulo?: T;
        whatsappAcao?: T;
        emailTitulo?: T;
        localizacaoTitulo?: T;
        localizacaoFallback?: T;
        horarioTitulo?: T;
        horarioFallback?: T;
        areasChapeu?: T;
        areasTitulo?: T;
        faqChapeu?: T;
        faqTitulo?: T;
        faq?:
          | T
          | {
              pergunta?: T;
              resposta?: T;
              id?: T;
            };
        segurancaChapeu?: T;
        segurancaTitulo?: T;
      };
  areas?:
    | T
    | {
        heroChapeu?: T;
        heroTitulo?: T;
        heroTexto?: T;
        heroImagem?: T;
        editorialChapeu?: T;
        editorialTitulo?: T;
        editorialTexto?: T;
        editorialImagem?: T;
        destaques?:
          | T
          | {
              texto?: T;
              icone?: T;
              id?: T;
            };
        processoChapeu?: T;
        processoTitulo?: T;
        processoEtapas?:
          | T
          | {
              titulo?: T;
              descricao?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              chapeu?: T;
              titulo?: T;
              texto?: T;
              botao?: T;
            };
      };
  paginasArea?:
    | T
    | {
        slug?: T;
        titulo?: T;
        tituloDestaque?: T;
        chapeu?: T;
        descricao?: T;
        icone?: T;
        notaHero?: T;
        servicosChapeu?: T;
        servicosTitulo?: T;
        servicos?:
          | T
          | {
              titulo?: T;
              descricao?: T;
              icone?: T;
              id?: T;
            };
        publicoTitulo?: T;
        publicos?:
          | T
          | {
              titulo?: T;
              descricao?: T;
              icone?: T;
              id?: T;
            };
        processoChapeu?: T;
        processoTitulo?: T;
        processoEtapas?:
          | T
          | {
              titulo?: T;
              descricao?: T;
              id?: T;
            };
        extrasChapeu?: T;
        extrasTitulo?: T;
        extras?:
          | T
          | {
              titulo?: T;
              descricao?: T;
              icone?: T;
              id?: T;
            };
        faqChapeu?: T;
        faqTitulo?: T;
        faq?:
          | T
          | {
              pergunta?: T;
              resposta?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              chapeu?: T;
              titulo?: T;
              texto?: T;
              botao?: T;
            };
        situacoes?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        documentosTitulo?: T;
        documentos?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}